version: '3.7'
services:

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "Asia/Bangkok"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - mariadb-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      #PMA_HOST: mariadb
      #PMA_USER: root
      #PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 10240000
      #PMA_ABSOLUTE_URI: https://db.domain.com
      TZ: "Asia/Bangkok"
    ports:
      - "8080:80"
    links:
      - mariadb:db
    networks:
      - mariadb-network
networks:
  mariadb-network:
